// NyxCode Arena — Benchmark Data
// All code examples and metrics

const SCENARIOS = {};

// ============================================================
// BLOG WITH AUTH
// ============================================================
SCENARIOS.blog = {
  name: "Blog with Auth",
  description: "Full-stack blog with user registration, login, posts CRUD, comments, and author relations.",
  metrics: {
    nyxcode: { tokens: 2921, lines: 30, files: 1, deps: 0 },
    nextjs:  { tokens: 5589, lines: 180, files: 8, deps: 12 },
    fastapi: { tokens: 4820, lines: 155, files: 7, deps: 9 }
  },
  code: { nyxcode: "", nextjs: "", fastapi: "" },
  fileTree: {
    nyxcode: ["\u{1F4C4} blog.nyx"],
    nextjs: [
      "\u{1F4C1} prisma/",
      "  \u{1F4C4} schema.prisma",
      "\u{1F4C1} app/",
      "  \u{1F4C4} layout.tsx",
      "  \u{1F4C4} page.tsx",
      "  \u{1F4C1} api/",
      "    \u{1F4C1} auth/",
      "      \u{1F4C1} register/route.ts",
      "      \u{1F4C1} login/route.ts",
      "    \u{1F4C1} posts/route.ts",
      "  \u{1F4C1} login/page.tsx",
      "  \u{1F4C1} register/page.tsx",
      "\u{1F4C1} lib/",
      "  \u{1F4C4} prisma.ts",
      "  \u{1F4C4} auth.ts",
      "\u{1F4C4} package.json",
      "\u{1F4C4} tsconfig.json",
      "\u{1F4C4} next.config.js"
    ],
    fastapi: [
      "\u{1F4C4} main.py",
      "\u{1F4C4} models.py",
      "\u{1F4C4} auth.py",
      "\u{1F4C4} database.py",
      "\u{1F4C4} schemas.py",
      "\u{1F4C1} templates/",
      "  \u{1F4C4} index.html",
      "  \u{1F4C4} login.html",
      "  \u{1F4C4} register.html",
      "\u{1F4C4} requirements.txt"
    ]
  }
};

SCENARIOS.blog.code.nyxcode = [
  "# blog.nyx \u2014 Full-stack blog in 30 lines",
  "table users {",
  "  name text required min=2 max=50",
  "  email text required unique format=email",
  "  password password required min=8",
  "  created auto",
  "}",
  "",
  "table posts {",
  "  title text required",
  "  body text required",
  "  author [users]",
  "  created auto",
  "}",
  "",
  "security {",
  "  table users",
  "  login email password",
  "  token jwt",
  "  protect /api/posts write",
  "}",
  "",
  'theme { colors { primary #667eea, bg #0a0a12, card #1a1a2e } }',
  "preset card { bg card, r 12px, p 2rem }",
  "",
  "page / {",
  "  section style={ mw 800px, mx auto, p 2rem } {",
  '    h1 "My Blog"',
  "    form /api/posts auth {",
  '      input title placeholder="Post title"',
  '      input body placeholder="Write something..."',
  '      submit "Publish"',
  "      success -> reload",
  "    }",
  "    data posts = get /api/posts {",
  '      loading -> p "Loading..."',
  '      empty -> p "No posts yet."',
  "    }",
  "    each posts -> div preset=card {",
  "      h3 .title",
  "      p .body",
  "      small .author.name",
  "    }",
  "  }",
  "}",
  "",
  "page /register {",
  "  section style={ mw 400px, mx auto, p 2rem } {",
  '    h1 "Register"',
  "    form /api/auth/register {",
  '      input name placeholder="Name"',
  '      input email placeholder="Email"',
  '      input password placeholder="Password"',
  '      submit "Sign Up"',
  "      success -> redirect /login",
  "    }",
  "  }",
  "}",
  "",
  "page /login {",
  "  section style={ mw 400px, mx auto, p 2rem } {",
  '    h1 "Login"',
  "    form /api/auth/login {",
  '      input email placeholder="Email"',
  '      input password placeholder="Password"',
  '      submit "Log In"',
  "      success -> redirect /",
  "    }",
  "  }",
  "}"
].join("\n");

SCENARIOS.blog.code.nextjs = [
  "// \u2500\u2500 Next.js 15 + Prisma Blog \u2500\u2500",
  "// 8+ files needed, showing key parts",
  "",
  "// prisma/schema.prisma",
  "generator client {",
  '  provider = "prisma-client-js"',
  "}",
  "datasource db {",
  '  provider = "sqlite"',
  '  url      = "file:./dev.db"',
  "}",
  "model User {",
  "  id       Int      @id @default(autoincrement())",
  "  name     String",
  "  email    String   @unique",
  "  password String",
  "  posts    Post[]",
  "  createdAt DateTime @default(now())",
  "}",
  "model Post {",
  "  id       Int      @id @default(autoincrement())",
  "  title    String",
  "  body     String",
  "  author   User     @relation(fields: [authorId], references: [id])",
  "  authorId Int",
  "  createdAt DateTime @default(now())",
  "}",
  "",
  "// app/api/auth/register/route.ts",
  "import { NextResponse } from 'next/server';",
  "import { prisma } from '@/lib/prisma';",
  "import bcrypt from 'bcryptjs';",
  "",
  "export async function POST(req: Request) {",
  "  const { name, email, password } = await req.json();",
  "  const hash = await bcrypt.hash(password, 12);",
  "  const user = await prisma.user.create({",
  "    data: { name, email, password: hash }",
  "  });",
  "  return NextResponse.json({ id: user.id });",
  "}",
  "",
  "// app/api/auth/login/route.ts",
  "import jwt from 'jsonwebtoken';",
  "import bcrypt from 'bcryptjs';",
  "export async function POST(req: Request) {",
  "  const { email, password } = await req.json();",
  "  const user = await prisma.user.findUnique({",
  "    where: { email }",
  "  });",
  "  if (!user) return NextResponse.json(",
  "    { error: 'Not found' }, { status: 404 }",
  "  );",
  "  const valid = await bcrypt.compare(password, user.password);",
  "  if (!valid) return NextResponse.json(",
  "    { error: 'Invalid' }, { status: 401 }",
  "  );",
  "  const token = jwt.sign(",
  "    { userId: user.id },",
  "    process.env.JWT_SECRET!",
  "  );",
  "  return NextResponse.json({ token });",
  "}",
  "",
  "// app/api/posts/route.ts",
  "import { NextResponse } from 'next/server';",
  "import { prisma } from '@/lib/prisma';",
  "import { verifyAuth } from '@/lib/auth';",
  "",
  "export async function GET() {",
  "  const posts = await prisma.post.findMany({",
  "    include: { author: {",
  "      select: { id: true, name: true, email: true }",
  "    }},",
  "    orderBy: { createdAt: 'desc' }",
  "  });",
  "  return NextResponse.json(posts);",
  "}",
  "",
  "export async function POST(req: Request) {",
  "  const user = await verifyAuth(req);",
  "  if (!user) return NextResponse.json(",
  "    { error: 'Unauthorized' }, { status: 401 }",
  "  );",
  "  const { title, body } = await req.json();",
  "  const post = await prisma.post.create({",
  "    data: { title, body, authorId: user.id }",
  "  });",
  "  return NextResponse.json(post, { status: 201 });",
  "}",
  "",
  "// app/page.tsx",
  "'use client';",
  "import { useState, useEffect } from 'react';",
  "",
  "export default function Home() {",
  "  const [posts, setPosts] = useState([]);",
  "  const [title, setTitle] = useState('');",
  "  const [body, setBody] = useState('');",
  "",
  "  useEffect(() => {",
  "    fetch('/api/posts').then(r => r.json())",
  "      .then(setPosts);",
  "  }, []);",
  "",
  "  const handleSubmit = async (e) => {",
  "    e.preventDefault();",
  "    const token = localStorage.getItem('token');",
  "    await fetch('/api/posts', {",
  "      method: 'POST',",
  "      headers: {",
  "        'Content-Type': 'application/json',",
  "        'Authorization': `Bearer ${token}`",
  "      },",
  "      body: JSON.stringify({ title, body })",
  "    });",
  "    location.reload();",
  "  };",
  "",
  "  return (",
  "    <main style={{ maxWidth: 800, margin: '0 auto' }}>",
  "      <h1>My Blog</h1>",
  "      <form onSubmit={handleSubmit}>",
  "        <input value={title}",
  '          onChange={e => setTitle(e.target.value)}',
  '          placeholder="Post title" />',
  "        <input value={body}",
  '          onChange={e => setBody(e.target.value)}',
  '          placeholder="Write something..." />',
  '        <button type="submit">Publish</button>',
  "      </form>",
  "      {posts.map(post => (",
  '        <div key={post.id} className="card">',
  "          <h3>{post.title}</h3>",
  "          <p>{post.body}</p>",
  "          <small>{post.author?.name}</small>",
  "        </div>",
  "      ))}",
  "    </main>",
  "  );",
  "}",
  "",
  "// + login/page.tsx, register/page.tsx,",
  "// lib/prisma.ts, lib/auth.ts, layout.tsx,",
  "// middleware.ts, package.json, tsconfig.json..."
].join("\n");

SCENARIOS.blog.code.fastapi = [
  "# \u2500\u2500 FastAPI + SQLAlchemy Blog \u2500\u2500",
  "# 7 files needed, showing key parts",
  "",
  "# models.py",
  "from sqlalchemy import (Column, Integer, String,",
  "    Text, DateTime, ForeignKey)",
  "from sqlalchemy.orm import relationship, declarative_base",
  "from datetime import datetime",
  "",
  "Base = declarative_base()",
  "",
  "class User(Base):",
  '    __tablename__ = "users"',
  "    id = Column(Integer, primary_key=True)",
  "    name = Column(String(50), nullable=False)",
  "    email = Column(String, unique=True, nullable=False)",
  "    password = Column(String, nullable=False)",
  "    created = Column(DateTime, default=datetime.utcnow)",
  '    posts = relationship("Post", back_populates="author")',
  "",
  "class Post(Base):",
  '    __tablename__ = "posts"',
  "    id = Column(Integer, primary_key=True)",
  "    title = Column(String, nullable=False)",
  "    body = Column(Text, nullable=False)",
  '    author_id = Column(Integer, ForeignKey("users.id"))',
  "    created = Column(DateTime, default=datetime.utcnow)",
  '    author = relationship("User", back_populates="posts")',
  "",
  "# auth.py",
  "from fastapi import Depends, HTTPException",
  "from fastapi.security import HTTPBearer",
  "from passlib.context import CryptContext",
  "import jwt, os",
  "",
  'pwd = CryptContext(schemes=["bcrypt"])',
  "security = HTTPBearer()",
  "",
  "def hash_password(pw: str) -> str:",
  "    return pwd.hash(pw)",
  "",
  "def verify_password(plain: str, hashed: str) -> bool:",
  "    return pwd.verify(plain, hashed)",
  "",
  "def create_token(user_id: int) -> str:",
  "    return jwt.encode(",
  '        {"user_id": user_id},',
  '        os.getenv("JWT_SECRET", "dev-secret"),',
  '        algorithm="HS256"',
  "    )",
  "",
  "def get_current_user(",
  "    token = Depends(security),",
  "    db = Depends(get_db)",
  "):",
  "    try:",
  "        payload = jwt.decode(token.credentials,",
  '            os.getenv("JWT_SECRET"), algorithms=["HS256"])',
  '        user = db.query(User).get(payload["user_id"])',
  "        if not user:",
  '            raise HTTPException(401, "Invalid token")',
  "        return user",
  "    except jwt.InvalidTokenError:",
  '        raise HTTPException(401, "Invalid token")',
  "",
  "# main.py",
  "from fastapi import FastAPI, Depends, HTTPException",
  "from sqlalchemy.orm import Session",
  "from pydantic import BaseModel, EmailStr",
  "",
  "app = FastAPI()",
  "",
  "class RegisterInput(BaseModel):",
  "    name: str",
  "    email: EmailStr",
  "    password: str",
  "",
  "class LoginInput(BaseModel):",
  "    email: EmailStr",
  "    password: str",
  "",
  "class PostInput(BaseModel):",
  "    title: str",
  "    body: str",
  "",
  '@app.post("/api/auth/register")',
  "def register(data: RegisterInput, db: Session = Depends(get_db)):",
  "    user = User(name=data.name, email=data.email,",
  "                password=hash_password(data.password))",
  "    db.add(user)",
  "    db.commit()",
  '    return {"id": user.id, "token": create_token(user.id)}',
  "",
  '@app.post("/api/auth/login")',
  "def login(data: LoginInput, db: Session = Depends(get_db)):",
  "    user = db.query(User).filter(",
  "        User.email == data.email).first()",
  "    if not user or not verify_password(",
  "        data.password, user.password):",
  '        raise HTTPException(401, "Invalid credentials")',
  '    return {"token": create_token(user.id)}',
  "",
  '@app.get("/api/posts")',
  "def list_posts(db: Session = Depends(get_db)):",
  "    posts = db.query(Post).all()",
  '    return [{"id": p.id, "title": p.title, "body": p.body,',
  '             "author": {"name": p.author.name}} for p in posts]',
  "",
  '@app.post("/api/posts", status_code=201)',
  "def create_post(data: PostInput,",
  "    user = Depends(get_current_user),",
  "    db: Session = Depends(get_db)):",
  "    post = Post(title=data.title, body=data.body,",
  "                author_id=user.id)",
  "    db.add(post)",
  "    db.commit()",
  '    return {"id": post.id}',
  "",
  "# + database.py, schemas.py, requirements.txt,",
  "# templates/ (Jinja2 or separate SPA)..."
].join("\n");

// ============================================================
// TODO APP
// ============================================================
SCENARIOS.todo = {
  name: "Todo App",
  description: "Todo list with CRUD operations, state management, and persistent storage.",
  metrics: {
    nyxcode: { tokens: 980, lines: 18, files: 1, deps: 0 },
    nextjs:  { tokens: 2450, lines: 95, files: 5, deps: 8 },
    fastapi: { tokens: 2100, lines: 82, files: 5, deps: 6 }
  },
  code: { nyxcode: "", nextjs: "", fastapi: "" },
  fileTree: {
    nyxcode: ["\u{1F4C4} todo.nyx"],
    nextjs: [
      "\u{1F4C1} prisma/",
      "  \u{1F4C4} schema.prisma",
      "\u{1F4C1} app/",
      "  \u{1F4C4} page.tsx",
      "  \u{1F4C1} api/",
      "    \u{1F4C1} todos/",
      "      \u{1F4C4} route.ts",
      "      \u{1F4C1} [id]/route.ts",
      "\u{1F4C1} lib/",
      "  \u{1F4C4} prisma.ts",
      "\u{1F4C4} package.json",
      "\u{1F4C4} tsconfig.json"
    ],
    fastapi: [
      "\u{1F4C4} main.py",
      "\u{1F4C4} models.py",
      "\u{1F4C4} database.py",
      "\u{1F4C4} schemas.py",
      "\u{1F4C4} requirements.txt"
    ]
  }
};

SCENARIOS.todo.code.nyxcode = [
  "# todo.nyx \u2014 Full-stack todo in 18 lines",
  "",
  "table todos {",
  "  title text required min=1",
  "  done bool default=false",
  "  created auto",
  "}",
  "",
  "theme { colors { primary #667eea, bg #0f172a, card #1e293b } }",
  "preset task { bg card, r 8px, p 1rem, mb 0.5rem }",
  "",
  "page / {",
  "  section style={ mw 500px, mx auto, p 2rem } {",
  '    h1 "My Todos \u{1F99E}"',
  "    form /api/todos {",
  '      input title placeholder="What needs doing?"',
  '      submit "Add"',
  "      success -> reload",
  "    }",
  "    data todos = get /api/todos {",
  '      empty -> p "Nothing to do! \u{1F389}"',
  "    }",
  "    each todos -> div preset=task flex=row between center {",
  "      span .title",
  '      button "\u2715" on:click -> delete /api/todos/.id',
  "    }",
  "  }",
  "}"
].join("\n");

SCENARIOS.todo.code.nextjs = [
  "// \u2500\u2500 Next.js 15 Todo App \u2500\u2500",
  "// 5+ files needed, showing key parts",
  "",
  "// prisma/schema.prisma",
  "model Todo {",
  "  id        Int      @id @default(autoincrement())",
  "  title     String",
  "  done      Boolean  @default(false)",
  "  createdAt DateTime @default(now())",
  "}",
  "",
  "// app/api/todos/route.ts",
  "import { prisma } from '@/lib/prisma';",
  "import { NextResponse } from 'next/server';",
  "",
  "export async function GET() {",
  "  const todos = await prisma.todo.findMany({",
  "    orderBy: { createdAt: 'desc' }",
  "  });",
  "  return NextResponse.json(todos);",
  "}",
  "",
  "export async function POST(req: Request) {",
  "  const { title } = await req.json();",
  "  if (!title?.trim()) {",
  "    return NextResponse.json(",
  "      { error: 'Title required' }, { status: 400 }",
  "    );",
  "  }",
  "  const todo = await prisma.todo.create({",
  "    data: { title }",
  "  });",
  "  return NextResponse.json(todo, { status: 201 });",
  "}",
  "",
  "// app/api/todos/[id]/route.ts",
  "export async function DELETE(",
  "  req: Request,",
  "  { params }: { params: { id: string } }",
  ") {",
  "  await prisma.todo.delete({",
  "    where: { id: parseInt(params.id) }",
  "  });",
  "  return NextResponse.json({ ok: true });",
  "}",
  "",
  "// app/page.tsx",
  "'use client';",
  "import { useState, useEffect } from 'react';",
  "",
  "export default function Home() {",
  "  const [todos, setTodos] = useState([]);",
  "  const [title, setTitle] = useState('');",
  "",
  "  const load = () =>",
  "    fetch('/api/todos').then(r => r.json())",
  "      .then(setTodos);",
  "",
  "  useEffect(() => { load(); }, []);",
  "",
  "  const add = async (e) => {",
  "    e.preventDefault();",
  "    await fetch('/api/todos', {",
  "      method: 'POST',",
  "      headers: { 'Content-Type': 'application/json' },",
  "      body: JSON.stringify({ title })",
  "    });",
  "    setTitle('');",
  "    load();",
  "  };",
  "",
  "  const remove = async (id) => {",
  "    await fetch(`/api/todos/${id}`, {",
  "      method: 'DELETE'",
  "    });",
  "    load();",
  "  };",
  "",
  "  return (",
  "    <main style={{ maxWidth: 500, margin: '0 auto' }}>",
  '      <h1>My Todos \u{1F99E}</h1>',
  "      <form onSubmit={add}>",
  "        <input value={title}",
  "          onChange={e => setTitle(e.target.value)}",
  '          placeholder="What needs doing?" />',
  '        <button type="submit">Add</button>',
  "      </form>",
  '      {todos.length === 0 && <p>Nothing to do! \u{1F389}</p>}',
  "      {todos.map(t => (",
  '        <div key={t.id} className="task">',
  "          <span>{t.title}</span>",
  "          <button onClick={() => remove(t.id)}>\u2715</button>",
  "        </div>",
  "      ))}",
  "    </main>",
  "  );",
  "}",
  "",
  "// + lib/prisma.ts, package.json, tsconfig.json..."
].join("\n");

SCENARIOS.todo.code.fastapi = [
  "# \u2500\u2500 FastAPI + SQLAlchemy Todo \u2500\u2500",
  "# 5 files needed, showing key parts",
  "",
  "# models.py",
  "from sqlalchemy import Column, Integer, String, Boolean, DateTime",
  "from sqlalchemy.orm import declarative_base",
  "from datetime import datetime",
  "",
  "Base = declarative_base()",
  "",
  "class Todo(Base):",
  '    __tablename__ = "todos"',
  "    id = Column(Integer, primary_key=True)",
  "    title = Column(String, nullable=False)",
  "    done = Column(Boolean, default=False)",
  "    created = Column(DateTime, default=datetime.utcnow)",
  "",
  "# main.py",
  "from fastapi import FastAPI, Depends, HTTPException",
  "from sqlalchemy.orm import Session",
  "from pydantic import BaseModel",
  "",
  "app = FastAPI()",
  "",
  "class TodoInput(BaseModel):",
  "    title: str",
  "",
  '@app.get("/api/todos")',
  "def list_todos(db: Session = Depends(get_db)):",
  "    return db.query(Todo).order_by(Todo.created.desc()).all()",
  "",
  '@app.post("/api/todos", status_code=201)',
  "def create_todo(data: TodoInput, db: Session = Depends(get_db)):",
  "    if not data.title.strip():",
  '        raise HTTPException(400, "Title required")',
  "    todo = Todo(title=data.title)",
  "    db.add(todo)",
  "    db.commit()",
  '    return {"id": todo.id}',
  "",
  '@app.delete("/api/todos/{todo_id}")',
  "def delete_todo(todo_id: int, db: Session = Depends(get_db)):",
  "    todo = db.query(Todo).get(todo_id)",
  "    if not todo:",
  '        raise HTTPException(404, "Not found")',
  "    db.delete(todo)",
  "    db.commit()",
  '    return {"ok": True}',
  "",
  "# + database.py, schemas.py, requirements.txt,",
  "# templates/index.html (or separate SPA)..."
].join("\n");

// ============================================================
// CHAT APP
// ============================================================
SCENARIOS.chat = {
  name: "Chat App",
  description: "Real-time chat with WebSocket, user auth, message history, and live updates.",
  metrics: {
    nyxcode: { tokens: 1520, lines: 25, files: 1, deps: 0 },
    nextjs:  { tokens: 4200, lines: 160, files: 9, deps: 14 },
    fastapi: { tokens: 3600, lines: 135, files: 7, deps: 10 }
  },
  code: { nyxcode: "", nextjs: "", fastapi: "" },
  fileTree: {
    nyxcode: ["\u{1F4C4} chat.nyx"],
    nextjs: [
      "\u{1F4C4} server.js (custom WS server)",
      "\u{1F4C1} prisma/",
      "  \u{1F4C4} schema.prisma",
      "\u{1F4C1} app/",
      "  \u{1F4C4} layout.tsx",
      "  \u{1F4C4} page.tsx",
      "  \u{1F4C1} api/",
      "    \u{1F4C1} auth/",
      "      \u{1F4C1} register/route.ts",
      "      \u{1F4C1} login/route.ts",
      "    \u{1F4C1} messages/route.ts",
      "  \u{1F4C1} login/page.tsx",
      "  \u{1F4C1} register/page.tsx",
      "\u{1F4C1} lib/",
      "  \u{1F4C4} prisma.ts",
      "  \u{1F4C4} auth.ts",
      "\u{1F4C4} package.json",
      "\u{1F4C4} tsconfig.json"
    ],
    fastapi: [
      "\u{1F4C4} main.py",
      "\u{1F4C4} models.py",
      "\u{1F4C4} auth.py",
      "\u{1F4C4} database.py",
      "\u{1F4C4} schemas.py",
      "\u{1F4C1} templates/",
      "  \u{1F4C4} index.html",
      "\u{1F4C4} requirements.txt"
    ]
  }
};

SCENARIOS.chat.code.nyxcode = [
  "# chat.nyx \u2014 Realtime chat in 25 lines",
  "",
  "table users {",
  "  name text required min=2",
  "  email text required unique format=email",
  "  password password required min=8",
  "}",
  "",
  "table messages {",
  "  text text required realtime",
  "  author [users]",
  "  created auto",
  "}",
  "",
  "security {",
  "  table users",
  "  login email password",
  "  token jwt",
  "  protect /api/messages write",
  "}",
  "",
  "theme { colors { primary #667eea, bg #0a0a12, card #1a1a2e, accent #00d4ff } }",
  "preset msg { bg card, r 12px, p 1rem, mb 0.5rem }",
  "",
  "page / {",
  "  section style={ mw 600px, mx auto, p 2rem, h 100vh, d flex, fd column } {",
  '    h1 "NyxChat \u{1F4AC}"',
  "    data msgs = live /api/messages auth {",
  '      loading -> p "Connecting..."',
  '      empty -> p "No messages yet. Say something!"',
  "    }",
  "    div style={ fg 1, oy auto } {",
  "      each msgs -> div preset=msg {",
  "        strong .author.name",
  "        p .text",
  "        small .created",
  "      }",
  "    }",
  "    form /api/messages auth {",
  '      input text placeholder="Type a message..."',
  '      submit "Send"',
  "      success -> clear",
  "    }",
  "  }",
  "}",
  "",
  "page /register {",
  "  section style={ mw 400px, mx auto, p 2rem } {",
  '    h1 "Join Chat"',
  "    form /api/auth/register {",
  '      input name placeholder="Name"',
  '      input email placeholder="Email"',
  '      input password placeholder="Password"',
  '      submit "Register"',
  "      success -> redirect /login",
  "    }",
  "  }",
  "}",
  "",
  "page /login {",
  "  section style={ mw 400px, mx auto, p 2rem } {",
  '    h1 "Login"',
  "    form /api/auth/login {",
  '      input email placeholder="Email"',
  '      input password placeholder="Password"',
  '      submit "Log In"',
  "      success -> redirect /",
  "    }",
  "  }",
  "}"
].join("\n");

SCENARIOS.chat.code.nextjs = [
  "// \u2500\u2500 Next.js 15 + Prisma Chat App \u2500\u2500",
  "// 9+ files needed, showing key parts",
  "",
  "// prisma/schema.prisma",
  "model User {",
  "  id       Int       @id @default(autoincrement())",
  "  name     String",
  "  email    String    @unique",
  "  password String",
  "  messages Message[]",
  "}",
  "model Message {",
  "  id       Int      @id @default(autoincrement())",
  "  text     String",
  "  author   User     @relation(fields: [authorId], references: [id])",
  "  authorId Int",
  "  created  DateTime @default(now())",
  "}",
  "",
  "// server.js (custom \u2014 Next.js has NO native WebSocket!)",
  "const { createServer } = require('http');",
  "const { parse } = require('url');",
  "const next = require('next');",
  "const { WebSocketServer } = require('ws');",
  "",
  "const app = next({ dev: process.env.NODE_ENV !== 'production' });",
  "const handle = app.getRequestHandler();",
  "",
  "app.prepare().then(() => {",
  "  const server = createServer((req, res) => {",
  "    handle(req, res, parse(req.url, true));",
  "  });",
  "  const wss = new WebSocketServer({ server });",
  "  const clients = new Set();",
  "  wss.on('connection', (ws) => {",
  "    clients.add(ws);",
  "    ws.on('close', () => clients.delete(ws));",
  "  });",
  "  global.broadcast = (data) => {",
  "    clients.forEach(client => {",
  "      if (client.readyState === 1)",
  "        client.send(JSON.stringify(data));",
  "    });",
  "  };",
  "  server.listen(3000);",
  "});",
  "",
  "// app/api/messages/route.ts",
  "export async function GET() {",
  "  const messages = await prisma.message.findMany({",
  "    include: { author: { select: { id: true, name: true } }},",
  "    orderBy: { created: 'asc' }",
  "  });",
  "  return NextResponse.json(messages);",
  "}",
  "",
  "export async function POST(req: Request) {",
  "  const user = await verifyAuth(req);",
  "  if (!user) return NextResponse.json(",
  "    { error: 'Unauthorized' }, { status: 401 });",
  "  const { text } = await req.json();",
  "  const msg = await prisma.message.create({",
  "    data: { text, authorId: user.id },",
  "    include: { author: { select: { id: true, name: true } }}",
  "  });",
  "  global.broadcast?.(msg);",
  "  return NextResponse.json(msg, { status: 201 });",
  "}",
  "",
  "// app/page.tsx",
  "'use client';",
  "import { useState, useEffect, useRef } from 'react';",
  "",
  "export default function Chat() {",
  "  const [msgs, setMsgs] = useState([]);",
  "  const [text, setText] = useState('');",
  "  const ws = useRef(null);",
  "",
  "  useEffect(() => {",
  "    fetch('/api/messages').then(r => r.json()).then(setMsgs);",
  "    ws.current = new WebSocket(`ws://${location.host}`);",
  "    ws.current.onmessage = (e) => {",
  "      const msg = JSON.parse(e.data);",
  "      setMsgs(prev => [...prev, msg]);",
  "    };",
  "    return () => ws.current?.close();",
  "  }, []);",
  "",
  "  const send = async (e) => {",
  "    e.preventDefault();",
  "    const token = localStorage.getItem('token');",
  "    await fetch('/api/messages', {",
  "      method: 'POST',",
  "      headers: {",
  "        'Content-Type': 'application/json',",
  "        'Authorization': `Bearer ${token}`",
  "      },",
  "      body: JSON.stringify({ text })",
  "    });",
  "    setText('');",
  "  };",
  "",
  "  return (",
  "    <main>",
  "      <h1>Chat</h1>",
  '      <div className="messages">',
  "        {msgs.map(m => (",
  "          <div key={m.id}>",
  "            <strong>{m.author.name}</strong>",
  "            <p>{m.text}</p>",
  "          </div>",
  "        ))}",
  "      </div>",
  "      <form onSubmit={send}>",
  "        <input value={text}",
  "          onChange={e => setText(e.target.value)}",
  '          placeholder="Type a message..." />',
  '        <button type="submit">Send</button>',
  "      </form>",
  "    </main>",
  "  );",
  "}",
  "",
  "// + auth routes, register/login pages,",
  "// lib/prisma.ts, lib/auth.ts, package.json,",
  "// tsconfig.json..."
].join("\n");

SCENARIOS.chat.code.fastapi = [
  "# \u2500\u2500 FastAPI + WebSocket Chat \u2500\u2500",
  "# 7 files needed, showing key parts",
  "",
  "# models.py",
  "from sqlalchemy import (Column, Integer, String,",
  "    Text, DateTime, ForeignKey)",
  "from sqlalchemy.orm import relationship, declarative_base",
  "from datetime import datetime",
  "",
  "Base = declarative_base()",
  "",
  "class User(Base):",
  '    __tablename__ = "users"',
  "    id = Column(Integer, primary_key=True)",
  "    name = Column(String(50), nullable=False)",
  "    email = Column(String, unique=True, nullable=False)",
  "    password = Column(String, nullable=False)",
  '    messages = relationship("Message", back_populates="author")',
  "",
  "class Message(Base):",
  '    __tablename__ = "messages"',
  "    id = Column(Integer, primary_key=True)",
  "    text = Column(Text, nullable=False)",
  '    author_id = Column(Integer, ForeignKey("users.id"))',
  "    created = Column(DateTime, default=datetime.utcnow)",
  '    author = relationship("User", back_populates="messages")',
  "",
  "# main.py",
  "from fastapi import FastAPI, WebSocket, Depends",
  "from typing import List",
  "import json",
  "",
  "app = FastAPI()",
  "active_connections: List[WebSocket] = []",
  "",
  '@app.websocket("/ws")',
  "async def websocket_endpoint(ws: WebSocket):",
  "    await ws.accept()",
  "    active_connections.append(ws)",
  "    try:",
  "        while True:",
  "            await ws.receive_text()",
  "    except:",
  "        active_connections.remove(ws)",
  "",
  "async def broadcast(message: dict):",
  "    for conn in active_connections:",
  "        await conn.send_json(message)",
  "",
  '@app.get("/api/messages")',
  "def get_messages(db = Depends(get_db)):",
  "    msgs = db.query(Message).order_by(Message.created).all()",
  '    return [{"id": m.id, "text": m.text,',
  '             "author": {"name": m.author.name},',
  '             "created": str(m.created)} for m in msgs]',
  "",
  '@app.post("/api/messages", status_code=201)',
  "async def create_message(",
  "    data: MessageInput,",
  "    user = Depends(get_current_user),",
  "    db = Depends(get_db)",
  "):",
  "    msg = Message(text=data.text, author_id=user.id)",
  "    db.add(msg)",
  "    db.commit()",
  '    await broadcast({"id": msg.id, "text": msg.text,',
  '        "author": {"name": user.name}})',
  '    return {"id": msg.id}',
  "",
  "# + auth.py, database.py, schemas.py,",
  "# requirements.txt, templates/ ..."
].join("\n");
